apiVersion: v1
kind: Namespace
metadata:
  name:  ns-posthub--env--
  labels: 
    name: ns-posthub--env--



---


apiVersion: apps/v1
kind: Deployment
metadata:
  name:  user-mongo
  namespace: ns-posthub--env--
  labels:
    name:  user-mongo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: user-mongo
  template:
    metadata:
      labels:
        name:  user-mongo
    spec:
      containers:
      - image:  mongo
        name:  user-mongo
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "1500m"
            memory: "2500M"    
        ports:
        - containerPort:  27017
          name:  user-mongo

---
kind: Service
apiVersion: v1
metadata:
  name:  user-mongo-service
  namespace: ns-posthub--env--
spec:
  selector:
    name: user-mongo
  type: ClusterIP
  ports:
  - name:  user-mongo
    port:  27020
    targetPort:  27017
