apiVersion: v1
kind: Namespace
metadata:
  name: ns-posthub--env--
  labels:
    name: ns-posthub--env--

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post--env--
  namespace: ns-posthub--env--
  labels:
    app: post--env--
spec:
  selector:
    matchLabels:
      app: post--env--
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: post--env--
    spec:
      containers:
        - name: post--env--
          image: __imageTag__
          env:
            - name: MONGO_URI
              value: mongodb://post-mongo-service:27020/post
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: JWTKEY
            - name: NATS_CLUSTER_IP
              value: posthubcluster
            - name: NATS_CLUSTER_IP
              valueFrom:
                fieldRef:
                  fieldpath: metadata.name
            - name: NATS_URL
              value: 'http://nats-eventhub-service:4222'
          resources:
            requests:
              cpu: 250m
              memory: 350Mi
            limits:
              cpu: 1100m
              memory: 700Mi
      readinessProbe:
        httpGet:
          path: /api/post/healthcheck
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
      ports:
        - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: post-service--env--
  namespace: ns-posthub--env--
spec:
  selector:
    app: post--env--
  type: ClusterIP
  ports:
    - name: post--env--
      port: 3000
      targetPort: 3000
