apiVersion: v1
kind: Namespace
metadata:
  name: ns-posthub--env--
  labels:
    name: ns-posthub--env--

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui--env--
  namespace: ns-posthub--env--
  labels:
    app: ui--env--
spec:
  selector:
    matchLabels:
      app: ui--env--
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui--env--
    spec:
      containers:
        - name: ui--env--
          image: __imageTag__
          resources:
            requests:
              cpu: 250m
              memory: 350Mi
            limits:
              cpu: 1100m
              memory: 900Mi
      ports:
        - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: ui-service--env--
  namespace: ns-posthub--env--
spec:
  selector:
    app: ui--env--
  type: ClusterIP
  ports:
    - name: ui--env--
      port: 3000
      targetPort: 3000
