apiVersion: v1
kind: Namespace
metadata:
  name: ns-posthub--env--
  labels:
    name: ns-posthub--env--

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users--env--
  namespace: ns-posthub--env--
  labels:
    app: users--env--
spec:
  selector:
    matchLabels:
      app: users--env--
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: users--env--
    spec:
      containers:
        - name: users--env--
          image: __imageTag__
          env:
            - name: MONGO_URI
              value: mongodb://users-mongo-service:27020/users
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: JWTKEY
          resources:
            requests:
              cpu: 250m
              memory: 350Mi
            limits:
              cpu: 1100m
              memory: 700Mi
      readinessProbe:
        httpGet:
          path: /api/users/healthcheck
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
      ports:
        - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: users-service--env--
  namespace: ns-posthub--env--
spec:
  selector:
    app: users--env--
  type: ClusterIP
  ports:
    - name: users--env--
      port: 3000
      targetPort: 3000
